apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: hr
  name: c
  labels:
    jobname: mycronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    metadata:
      name: myjob
      labels:
        podname: myjobpod
    spec:
      parallelism: 2
      completions: 4
      template:
        metadata:
          labels:
            podname: mycronjobpod
        spec:
          restartPolicy: OnFailure
          containers:
          - name: containerone
            image: busybox
            args:
            - /bin/sh
            - -c
            - echo "started.."; sleep 20; echo "going to die...";

