apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp10deployment
  labels:
    version: v1
    appname: webapplication10
spec:
  replicas: 3
  template:
    metadata:
      name: webapp10pods
      labels:
        version: v1
        appname: financev1
    spec:
      containers:
      - name: containerone
        image: mondayacr.azurecr.io/webapplication10:latest
        ports:
        - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
        version: v1
        appname: financev1
