apiVersion: v1
kind: Pod
metadata:
  name: envpod2
  labels:
    servicetype: nodeportpod
spec:
  containers:
  - name: mycontainer
    image: busybox
    args:
    - /bin/sh
    - -c
    - while true; do echo "message from pod"; echo $(abcd); echo $(ritesh); sleep 5; done
    envFrom:
    - configMapRef:
        name: firstconfigmap10

